/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface WcTypeme {
    'backspaceDelay': number;
    'childList': string;
    'cursorBlinkSpeed': number;
    'cursorCharacter': string;
    'deleteSpeed': number;
    'hideCursor': boolean;
    'loop': boolean;
    'mainClassName': string;
    'onAnimationEnd': () => void;
    'startAnimation': boolean;
    'strings': any;
    'typingSpeed': number;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLWcTypemeElement extends Components.WcTypeme, HTMLStencilElement {}
  var HTMLWcTypemeElement: {
    prototype: HTMLWcTypemeElement;
    new (): HTMLWcTypemeElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'wc-typeme': HTMLWcTypemeElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface WcTypeme extends JSXBase.HTMLAttributes<HTMLWcTypemeElement> {
    'backspaceDelay'?: number;
    'childList'?: string;
    'cursorBlinkSpeed'?: number;
    'cursorCharacter'?: string;
    'deleteSpeed'?: number;
    'hideCursor'?: boolean;
    'loop'?: boolean;
    'mainClassName'?: string;
    'onAnimationEnd'?: () => void;
    'startAnimation'?: boolean;
    'strings'?: any;
    'typingSpeed'?: number;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'wc-typeme': WcTypeme;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


